[tool.poetry]
name = "empanadas"
version = "0.1.0"
description = "hand crafted ISOs with love and spice"
authors = ["Louis Abel <louis@rockylinux.org>", "Neil Hanlon <neil@rockylinux.org>"]

[tool.poetry.dependencies]
python = "^3.10"
rpm-py-installer = "^1.1.0"
PyYAML = "^6.0"
Jinja2 = "^3.1.2"
productmd = "^1.33"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
sync-from-peridot = "empanadas.scripts.sync-from-peridot:run"
sync-from-peridot-test = "empanadas.scripts.sync-from-peridot-test:run"
sync-sig = "empanadas.scripts.sync-sig:run"
build-iso = "empanadas.scripts.build-iso:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
