---
'8':
  revision: '8.6'
  rclvl: 'RC2'
  allowed_arches:
    - x86_64
    - aarch64
  provide_multilib: False
  project_id: ''
  required_packages:
    - 'lorax'
    - 'genisoimage'
    - 'isomd5sum'
  repo_symlinks:
    devel: 'Devel'
    NFV: 'nfv'
  renames: {}
  all_repos:
    - 'BaseOS'
    - 'AppStream'
    - 'PowerTools'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
    - 'extras'
    - 'devel'
    - 'plus'
    - 'rockyrpi'
  no_comps_or_groups:
    - 'extras'
    - 'devel'
    - 'plus'
    - 'rockyrpi'
  comps_or_groups:
    - 'BaseOS'
    - 'AppStream'
    - 'PowerTools'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
  has_modules:
    - 'AppStream'
    - 'PowerTools'
  repoclosure_map:
    arches:
      x86_64: '--arch=x86_64 --arch=athlon --arch=i686 --arch=i586 --arch=i486 --arch=i386 --arch=noarch'
      aarch64: '--arch=aarch64 --arch=noarch'
      ppc64le: '--arch=ppc64le --arch=noarch'
      s390x: '--arch=s390x --arch=noarch'
    repos:
      BaseOS: []
      AppStream:
        - BaseOS
      PowerTools:
        - BaseOS
        - AppStream
      HighAvailability:
        - BaseOS
        - AppStream
      ResilientStorage:
        - BaseOS
        - AppStream
      RT:
        - BaseOS
        - AppStream
      NFV:
        - BaseOS
        - AppStream
...
