---
'9':
  revision: '9.0'
  rclvl: 'RC1'
  allowed_arches:
    - x86_64
    - aarch64
    - ppc64le
    - s390x
  provide_multilib: True
  project_id: '55b17281-bc54-4929-8aca-a8a11d628738'
  required_packages:
    - 'lorax'
    - 'genisoimage'
    - 'isomd5sum'
  repo_symlinks:
    devel: 'Devel'
    NFV: 'nfv'
  renames:
    all: 'nplb'
  all_repos:
    - 'all'
    - 'BaseOS'
    - 'AppStream'
    - 'CRB'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
    - 'SAP'
    - 'SAPHANA'
    - 'extras'
    - 'devel'
    - 'plus'
  no_comps_or_groups:
    - 'all'
    - 'extras'
    - 'devel'
    - 'plus'
  comps_or_groups:
    - 'BaseOS'
    - 'AppStream'
    - 'CRB'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
    - 'SAP'
    - 'SAPHANA'
  has_modules:
    - 'AppStream'
    - 'CRB'
  repoclosure_map:
    BaseOS: []
    AppStream:
      - BaseOS
    CRB:
      - BaseOS
      - AppStream
    HighAvailability:
      - BaseOS
      - AppStream
    ResilientStorage:
      - BaseOS
      - AppStream
    RT:
      - BaseOS
      - AppStream
    NFV:
      - BaseOS
      - AppStream
    SAP:
      - BaseOS
      - AppStream
      - HighAvailability
    SAPHANA:
      - BaseOS
      - AppStream
      - HighAvailability
...
